version: '3.8'
services:
    postfix:
        build:
            context: ./
            dockerfile: Dockerfile
        image: debian-11.6-postfix:latest
        ports:
            - "25:25"
        volumes:
            - type: bind
              source: ./log
              target: /var/log/postfix